sudo: require
language: python
dist: trusty

install:
  - sudo apt-get install libx11-dev libxtst-dev libxinerama-dev libxkbcommon-dev python-pytest xdotool bash xfonts-base xterm

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - xterm -l -e tests/travis_tests_within_xterm.sh
  - cat Xterm.log*
  - ls -lta success
